Fix build error due to uninitialized read_req
facebook/rocksdb pull request #10312
Opened 2022-07-06 03:41 UTC by JunHe77

GCC-12 has strick check on variables, and thus
build fails when it finds read_req is not properly
initialized (-Werror=maybe-uninitialized). Add
default value to fix this.

Change-Id: Ib8a9085e2d613ee7b943b58a6a58e1bc351725d7
Signed-off-by: Jun He <jun.he@arm.com>

2022-07-06 18:47 UTC, ajkr approved these changes
LGTM

2022-07-15 05:15 UTC, riversand963 requested changes
@JunHe77 thanks for the contribution. Can you fix the linter error?

2022-07-15 10:35 UTC, JunHe77 commented
@riversand963 , I cannot access the internal linter log. Would it be OK for you to post that warning log here? Thanks.

2022-07-22 14:44 UTC, riversand963 approved these changes

2022-07-22 16:28 UTC, closed without merging