Potentially deflake DBWALTest.FixSyncWalOnObseletedWalWithNewManifestCausingMissingWAL
facebook/rocksdb pull request #11016
Opened 2022-12-04 06:41 UTC by hx235

**Context/Summary:**
I accidentally observed this test failure https://app.circleci.com/pipelines/github/facebook/rocksdb/21985/workflows/5f6cc355-78c1-46d8-89ee-0fd679725a8a/jobs/540878 that can't be repro-ed. It belongs to a recent PR of mine https://github.com/facebook/rocksdb/pull/10892/files, which manually sets a log threshold to force new manifest creation. This is unreliable so I decided to use sync point to force new manifest creation.

**Test plan:**
make check

2022-12-05 18:09 UTC, ajkr requested changes
I think it is reproducible. Can you try this patch?

```
diff --git a/db/db_impl/db_impl_files.cc b/db/db_impl/db_impl_files.cc
index 9834ff4b2..a6d24dbdb 100644
--- a/db/db_impl/db_impl_files.cc
+++ b/db/db_impl/db_impl_files.cc
@@ -315,6 +315,8 @@ void DBImpl::FindObsoleteFiles(JobContext* job_context, bool force,
     }
     log_write_mutex_.Unlock();
     mutex_.Unlock();
+    bg_cv_.SignalAll();
+    usleep(10000);
     TEST_SYNC_POINT_CALLBACK("FindObsoleteFiles::PostMutexUnlock", nullptr);
     log_write_mutex_.Lock();
     while (!logs_.empty() && logs_.front().number < min_log_number) {
```

2022-12-06 21:25 UTC, pdillinger approved these changes
Test still fails without original fix, so LGTM

(Not familiar enough with this area to know if the test can be simplified)

2022-12-06 23:31 UTC, ajkr approved these changes
LGTM too. This test could use higher level APIs (after all, it is a DB level test) to avoid so many sync points

Just to record the rough ideas. `ASSERT_OK(static_cast_with_check<DBImpl>(db)->TEST_WaitForBackgroundWork());` after the `Flush()` (see #9617) may be able to replace both the dependencies. Small max_manifest_file_size and verifying manifest changed (via some API?) could replace the ProcessManifestWrites callback. wal_file_path also seems accessible via some get files API

2022-12-06 23:49 UTC, ajkr commented
> verifying manifest changed (via some API?) could replace the ProcessManifestWrites callback

Comparing `dbfull()->TEST_Current_Manifest_FileNo()` before vs. after looks like a good API for it

2022-12-07 02:33 UTC, closed without merging

2023-01-22 19:37 UTC, ajkr commented
> This test could use higher level APIs (after all, it is a DB level test) to avoid so many sync points


@hx235 I hope this is tried or explicitly rejected, in which case I can try it

2023-01-23 19:02 UTC, hx235 commented
@ajkr  - Hi - sorry for some reason I forgot to follow up on this. Will try it this week. Any blocking issue that you'd like me to try it in a day or two (instead of by this week)?

2023-01-30 16:50 UTC, hx235 commented
> > Any blocking issue that you'd like me to try it in a day or two (instead of by this week)?
> 
> No, I was just reminded for unrelated reasons that our code is difficult to refactor, and I think excessive sync points is one reason (of many).

Sounds good! Will give this a better try once I am back from my trip/PTO