Support Clip DB to KeyRange
facebook/rocksdb pull request #11379
Opened 2023-04-13 09:36 UTC by mayuehappy

This PR is part of the request https://github.com/facebook/rocksdb/issues/11317.
(Another part is https://github.com/facebook/rocksdb/pull/11378)

ClipDB() will clip the entries in the CF according to the range [begin_key, end_key). All the entries outside this range will be completely deleted (including tombstones).
 This feature is mainly used to ensure that there is no overlapping Key when calling CreateColumnFamilyWithImports() to import multiple CFs.

When Calling ClipDB [begin, end), there are the following steps

1.  Quickly and directly delete files without overlap
 DeleteFilesInRanges(nullptr, begin) + DeleteFilesInRanges(end, nullptr)
2. Delete the Key outside the range
Delete[smallest_key, begin) + Delete[end, largest_key]
3. Delete the tombstone through Manul Compact
CompactRange(option, nullptr, nullptr)

2023-04-25 04:00 UTC, cbi42 reviewed
Thanks for the contribution! Overall approach looks good to me. Left comments for some details.

2023-04-25 14:43 UTC, mayuehappy commented
> 
@cbi42 
Thanks a lot for review, I updated some code and left some comments, please have a look

2023-04-25 14:46 UTC, mayuehappy commented on db/db_impl/db_impl.cc
> +  cfd->current()->GetSstFilesBoundaryKeys(&smallest_user_key, &largest_user_key);
Thanks for the reminder, but I encountered another issue. When I tried to Stop writes to the DB by entering both write threads, I found that the deteleRange in clipDB operation would also be stopped. So I just flush the memtable and i didn't disable write here. Can we add this to the description of the API ?

2023-04-26 08:04 UTC, mayuehappy commented on db/db_clip_test.cc
> +      if (begin_key.compare(md.smallestkey) <= 0 &&
I found that the smallestkey in SstFileMetaData is std::string, so is it enough for us to directly compare?

2023-05-08 20:36 UTC, cbi42 requested changes
Sorry for the delay, added a couple more comments.

2023-05-08 20:36 UTC, cbi42 commented on db/db_impl/db_impl.cc
> +      status = AtomicFlushMemTables(flush_opts, FlushReason::kGetLiveFiles,
We should use kOthers or kDeleteFiles for flush reason. I think `entered_write_thread` should be false since we are not in write thread.

2023-05-08 20:36 UTC, cbi42 commented on db/db_impl/db_impl.cc
> +  cfd->current()->GetSstFilesBoundaryKeys(&smallest_user_key, &largest_user_key);
Yeah I think it's probably easier and cleaner to just include in API contract that there should not be concurrent updates.

2023-05-08 20:36 UTC, cbi42 commented on db/db_impl/db_impl.cc
> +    InstrumentedMutexLock l(&mutex_);
We should only need mutex_ around `cfd->current()->GetSstFilesBoundaryKeys(&smallest_user_key, &largest_user_key);` now.

2023-05-08 20:36 UTC, cbi42 commented on db/db_impl/db_impl.cc
> +  status = CompactRange(compact_options, nullptr, nullptr);
Yes, I plan to make this change sometime.

2023-05-08 20:36 UTC, cbi42 commented on db/db_impl/db_impl.h
> +  // virtual Status CreateColumnFamilyWithImports(
Remove this?

2023-05-08 20:36 UTC, cbi42 requested changes
Sorry for the delay, added a couple more comments.

2023-05-09 06:34 UTC, mayuehappy commented on db/db_impl/compacted_db_impl.h
> +  virtual Status ClipDB(ColumnFamilyHandle* /*column_family*/,
I think "ClipColumnFamily" is good, and I have updated the changes

2023-05-09 06:37 UTC, mayuehappy commented
@cbi42 thanks again for the review , I made some changes according to your suggestion, please take a look

2023-05-13 06:58 UTC, cbi42 approved these changes
LGTM thanks! Just need to update HISTORY.md.

2023-05-13 06:59 UTC, cbi42 approved these changes
LGTM thanks! Just need to update HISTORY.md.

2023-05-15 03:31 UTC, mayuehappy commented
> LGTM thanks! Just need to update HISTORY.md.

@cbi42 Thanks very much, I have updated it

2023-05-15 20:30 UTC, cbi42 commented
> > LGTM thanks! Just need to update HISTORY.md.
> 
> @cbi42 Thanks very much, I have updated it

Could you rebase and edit HISTORY.md again? auto-merge seems to place the line you added under 8.2 release section instead of the unreleased section.

2023-05-18 20:29 UTC, closed without merging