Add bounds checking to WBWIIteratorImpl and respect bounds of ReadOptions in Transaction
facebook/rocksdb pull request #11680
Opened 2023-08-06 13:22 UTC by ywave620

Fix https://github.com/facebook/rocksdb/issues/11607 and https://github.com/facebook/rocksdb/issues/11679

Summary:

Add bounds checking to `WBWIIteratorImpl`, which will be reflected in `BaseDeltaIterator::delta_iterator_::Valid()`, just like `BaseDeltaIterator::base_iterator_::Valid()`. In this way, the two sub itertors become more aligned from `BaseDeltaIterator`'s respective. Like `DBIter`, the added bounds checking caps in either bound when seeking and disvalidates the iterator when the lower bound is past or the upper bound is reached.

Test Plan:

- A simple test added to write_batch_with_index_test.cc to exercies the bounds checking in `WBWIIteratorImpl` individually.
- A sophisticated test added to transaction_test.cc to assert that `Transaction` with different write policies honor bounds in `ReadOptions`. It should be so as long as the  `BaseDeltaIterator` is correctly coordinating the two sub iterators to perform iterating and bounds checking.

2023-08-07 19:37 UTC, ajkr commented
> Add bounds checking to WBWIIteratorImpl, which will be reflected in BaseDeltaIterator::delta_iterator_::Valid()

Interesting timing - https://github.com/facebook/rocksdb/pull/11662#discussion_r1285252595. Does this PR also fix the two issues mentioned in #11662?

2023-08-07 19:40 UTC, cz2h commented
> > Add bounds checking to WBWIIteratorImpl, which will be reflected in BaseDeltaIterator::delta_iterator_::Valid()
> 
> Interesting timing - [#11662 (comment)](https://github.com/facebook/rocksdb/pull/11662#discussion_r1285252595). Does this PR also fix the two issues mentioned in #11662?

I think so. This PR also provide feature for lower_bound as well. Looks like multiple issue is pointing to the same fix.

2023-08-08 02:09 UTC, ywave620 commented
@cz2h Thanks for the information. I agree with that this PR can be a replacer for the one you open, https://github.com/facebook/rocksdb/pull/11662, and could I move the test you wrote here?

2023-08-08 03:07 UTC, cz2h commented
> @cz2h Thanks for the information. I agree with that this PR can be a replacer for the one you open, #11662, and could I move the test you wrote here?

Please do, thanks.

2023-08-08 17:18 UTC, cbi42 commented on utilities/write_batch_with_index/write_batch_with_index_internal.h
> +      skip_list_iter_.SeekForPrev(&search_entry);
It seems the iterator can incorrectly return a key equal to `iterate_upper_bound_`. Maybe we can just do SeekToLast()?

2023-08-18 20:40 UTC, cbi42 requested changes

2023-08-18 20:40 UTC, cbi42 commented on utilities/write_batch_with_index/write_batch_with_index_internal.h
> +    out_of_bound_ = false;
Need to check upper bound too? Other Seek*() calls also miss a similar check.

2023-08-18 20:40 UTC, cbi42 commented on utilities/write_batch_with_index/write_batch_with_index_internal.h
> +      skip_list_iter_.SeekForPrev(&search_entry);
Do you think this can happen?

2023-09-26 16:38 UTC, cbi42 commented
> @cbi42 Any plan to move this forward? (BTW, the CI failed on installing dependencies)

Hi - sorry for the delay. I plan to finish reviewing this week.

2023-09-30 22:07 UTC, cbi42 commented on utilities/write_batch_with_index/write_batch_with_index_internal.h
> +      skip_list_iter_.SeekForPrev(&search_entry);
From https://github.com/facebook/rocksdb/blob/d98a9cfb27dbffb4f7a7ab173b366dd626c2f721/db/write_batch.cc#L11-L12, it seems entries won't have offset = 0. However, I feel it's safer not to assume this, and just call SeekToLast().

2023-09-30 22:08 UTC, cbi42 commented
> @cbi42 Any plan to move this forward? (BTW, the CI failed on installing dependencies)

@ywave620 There are a few comments that are still not addressed, can you take a look?

2023-10-02 17:22 UTC, cbi42 commented on utilities/write_batch_with_index/write_batch_with_index_internal.h
> +    out_of_bound_ = false;
@ywave620 I don't think this is addressed yet. See the following unit test:
```
TEST_P(WriteBatchWithIndexTest, CheckBounds) {
  Status s = OpenDB();
  ASSERT_OK(s);
  KVMap empty_map;
  // writes that should be observed by BaseDeltaIterator::delta_iterator_
  ASSERT_OK(batch_->Put("c", "cc"));
  ReadOptions ro;
  ro.iterate_lower_bound = new Slice("a");
  ro.iterate_upper_bound = new Slice("b");
  std::unique_ptr<Iterator> iter(batch_->NewIteratorWithBase(
      db_->DefaultColumnFamily(), new KVIter(&empty_map), &ro));
  iter->SeekToFirst();
// This assert fails
  ASSERT_FALSE(iter->Valid());
  delete ro.iterate_lower_bound;
  delete ro.iterate_upper_bound;
}
```

2023-10-02 17:23 UTC, cbi42 requested changes
https://github.com/facebook/rocksdb/pull/11680#discussion_r1342960097

2023-10-03 03:26 UTC, cbi42 commented
I think the additional bounds check also apply to Seek and SeekForPrev in addition to SeekTo{First,Last}.

2023-10-03 07:33 UTC, ywave620 commented
> I think the additional bounds check also apply to Seek and SeekForPrev in addition to SeekTo{First,Last}.

Also adopted, PTAL.

2023-10-04 08:44 UTC, adamretter commented
@ywave620 May I ask if this will also cover the previous work done in https://github.com/facebook/rocksdb/pull/7214

2023-10-04 15:03 UTC, ywave620 commented
> @ywave620 May I ask if this will also cover the previous work done in #7214 please?

Yes. But this PR takes care more than that. And sorry, I didn't know it when I started this work.

2023-10-04 16:03 UTC, adamretter commented
@ywave620 Thank you. I will just be happy if the problem is fixed and the code is merged :-)

2023-10-04 16:52 UTC, cbi42 approved these changes
LGTM, thanks!

2023-10-05 15:24 UTC, ywave620 commented
@cbi42 Thanks for your detail review. Is this ready to be merged? :)

2023-10-05 16:56 UTC, cbi42 commented
@ywave620 Could you also add a change log under https://github.com/facebook/rocksdb/tree/main/unreleased_history?

Besides that, it just needs internal review now.

2023-10-17 02:08 UTC, ywave620 commented
@cbi42 Hey, is there any news? :)

2023-10-17 02:18 UTC, ajkr commented
> Besides that, it just needs internal review now.

> @cbi42 Hey, is there any news? :)

The internal reviewer is me, but I haven't gotten to it yet. Probably can do it tomorrow

2023-10-18 22:42 UTC, ajkr approved these changes
Great work, thanks!

2023-10-18 22:42 UTC, ajkr commented on utilities/write_batch_with_index/write_batch_with_index_internal.h
> +  bool AfterUpperBound(const Slice* k) const {
I'd call it `AtOrAfterUpperBound()`

2023-10-20 12:40 UTC, ywave620 commented
@ajkr The branch goes out-of-date once again, I can't keep it synchronous consistently, please update it before you are going to merge :)

2023-10-20 20:31 UTC, closed without merging