Fix database open with column family.
facebook/rocksdb pull request #12167
Opened 2023-12-20 16:46 UTC by rhubner

When is RocksDB open with column family descriptors, the default column family must be set properly. If not, then the flush operation will fail.

2023-12-21 10:15 UTC, adamretter requested changes
In general this looks great thanks @rhubner, just two small changes.

2023-12-21 10:15 UTC, adamretter commented on java/src/main/java/org/rocksdb/RocksDB.java
> +      throw new RocksDBException("No default column family");
message -> "You must provide the default column family in your columnFamilyDescriptors"

2023-12-21 10:29 UTC, adamretter commented on java/src/main/java/org/rocksdb/RocksDB.java
> +      throw new RocksDBException("No default column family");
Let's move the check for the default column family before the `open` in the loop for the descriptors

2024-01-23 21:44 UTC, adamretter approved these changes
LGTM. Thanks @rhubner

2024-01-25 22:33 UTC, cbi42 approved these changes

2024-01-26 17:16 UTC, closed without merging