Fix typo in CMakeList.
facebook/rocksdb pull request #12247
Opened 2024-01-18 16:10 UTC by rhubner

Fix #12237

2024-01-23 21:20 UTC, adamretter requested changes
I think a small fix is still needed in `Findzstd.cmake`.
It might also be worth checking the other files in `cmake/modules/` as well?

2024-01-23 21:20 UTC, adamretter commented on CMakeLists.txt
> +    include_directories(${ZSTD_INCLUDE_DIRS})
I think this also needs fixing in `cmake/modules/Findzstd.cmake` where it seems to be in mixed-case.

2024-01-24 17:20 UTC, adamretter approved these changes
Now LGTM. Thanks @rhubner

2024-01-24 17:21 UTC, adamretter commented
@ajkr @pdillinger Can we get this one imported please?

2024-01-24 23:22 UTC, ajkr approved these changes

2024-01-25 20:39 UTC, closed without merging

2024-04-02 09:22 UTC, georgthegreat commented
This PR broke nixpkgs build. It looks like their version of zstd does not export ZSTD_INCLUDE_DIR

2024-04-02 16:06 UTC, georgthegreat commented
We have an internal system built atop of nixpkgs.
I am receiving the following error from it:

```
-- Found assembler: /nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/gcc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/90h6k8ylkgn81k10190v5c9ldyjpzgl9-gcc-wrapper-12.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: /nix/store/8xgb8phqmfn9h971q7dg369h647i1aa0-zlib-1.3/lib/libz.so (found version "1.3")
-- Found BZip2: /nix/store/155qsyx1mv11fsi48nz4dlc0vh1a3drx-bzip2-1.0.8/lib/libbz2.so (found version "1.0.8")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found lz4: /nix/store/874gxh0sgwkbwb7nfbp72sn7a058b7sa-lz4-1.9.4/lib/liblz4.so
CMake Error at /nix/store/vnhl4zdy7igx9gd3q1d548vwzz15a9ma-cmake-3.27.7/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find zstd (missing: ZSTD_INCLUDE_DIRS)
Call Stack (most recent call first):
  /nix/store/vnhl4zdy7igx9gd3q1d548vwzz15a9ma-cmake-3.27.7/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findzstd.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:167 (find_package)
```

I have worked it around by adding the following:
```
  cmakeFlags = attrs.cmakeFlags ++ [
    # Configuration fails otherwise as ZSTD_INCLUDE_DIRS is checked instead of ZSTD_INCLUDE_DIR
    "-DZSTD_INCLUDE_DIRS=${zstd.dev}"
  ];
```

I am not quite familiar with cmake internals to debug this.

2024-04-10 06:54 UTC, rhubner commented
Hello @georgthegreat and sorry for late reply,

Unfortunately I don't know nixos, but I can confirm that we recently changed the CMake build script. The refactor follows the pattern which we used to specify include dir for other libraries. Your fix with `"-DZSTD_INCLUDE_DIRS=${zstd.dev}"` makes sense and sounds legit for me. What I don't understand, how did you build it before without providing libzstd include path.

About CMake. During the build script generation with CMake, you can specify path where you have your libzstd. This allows you to use your version of zstd and not for example system/distribution version. I assume that when you are building nixos, you also build libzstd and then CMake needs to know where it is, if it's not in the default search path.

Radek

2024-04-13 12:43 UTC, georgthegreat commented
I have tried to understand why previous version worked, but I was unable to get to the root of it.
It looks like CMake's find_package does not provide any include-related variables out of the box, so it is up to the specific package manager to decide whether to provide this variables and how to name them.

I agree that `-DZSTD_INCLUDE_DIRS` solution solves the problems.
I am fine with keeping it.