don't run ZSTD_TrainDictionary in BlockBasedTableBuilder if there isn't compression needed
facebook/rocksdb pull request #12453
Opened 2024-03-18 13:49 UTC by kwadhwa18

fix for #12409

### Issue

ZSTD_TrainDictionary [[link](https://github.com/facebook/rocksdb/blob/a53ed916917fe79a6c3f07313ec7a3fa85ae6dc4/table/block_based/block_based_table_builder.cc#L1894)] runs for SSTFileWriter::Finish even when bottommost_compression option is set to kNoCompression. This reduces throughput for SstFileWriter::Finish

We construct rocksdb options using ZSTD compression for levels including 2 and above. For levels 0 and 1, we set it to kNoCompression. We also set zstd_max_train_bytes to a non-zero positive value (which is applicable for levels with ZSTD compression enabled). These options are used for the database and also passed to SstFileWriter for creating sst files to be later added to that database. Since the BlockBasedTableBuilder::Finish [[link](https://github.com/facebook/rocksdb/blob/a53ed916917fe79a6c3f07313ec7a3fa85ae6dc4/table/block_based/block_based_table_builder.cc#L1892)] only checks for zstd_max_train_bytes to be non-zero positive value, it runs ZSTD_TrainDictionary even when it shouldn't since SSTFileWriter is operating at bottommost level

### Fix

If compression_type is set to kNoCompression, then don't run ZSTD_TrainDictionary and dictionary building

### Testing

I see we have tests for sst file writer with compression type set/unset. Let me know if it isn't covered and I can extend

2024-03-18 21:11 UTC, ajkr requested changes

2024-03-18 21:13 UTC, ajkr commented on table/block_based/block_based_table_builder.cc
> +                                                       : State::kUnbuffered),
Btw, I mean we should bring it back in addition to the condition you have added here, not revert

2024-03-19 17:30 UTC, kwadhwa18 commented on table/block_based/block_based_table_builder.cc
> +               || tbo.compression_type != kNoCompression)
I was confused by the previous comment regarding the test failure

2024-03-19 22:57 UTC, ajkr commented on db/db_block_cache_test.cc
> +  options.compression = kLZ4Compression;
This test needs to be conditionally compiled now. Example: https://github.com/facebook/rocksdb/blob/fc40165614e3aecc1475d61f895f508b28247c0d/utilities/blob_db/blob_db_test.cc#L634-L725

2024-03-20 04:35 UTC, ajkr approved these changes
LGTM, thanks!

2024-03-20 18:13 UTC, closed without merging