Clarify `inplace_update_support` with DeleteRange and reenable `inplace_update_support` in crash test
facebook/rocksdb pull request #12577
Opened 2024-04-23 21:45 UTC by hx235

**Context/Summary:**
Our crash test recently surfaced incompatibilities between DeleteRange and inplace_update_support. Incorrect read result will be returned after insertion into memtables already contain delete range data.

This PR is to clarify this in API and re-enable `inplace_update_support` in crash test with sanitization. 

**Test:**
CI

2024-04-24 18:24 UTC, ajkr approved these changes

2024-04-24 18:24 UTC, ajkr commented on include/rocksdb/advanced_options.h
> +  // (1) DeleteRange
It might be easier to list the read features it is intended to work with: (1) non-snapshot `Get()`

2024-04-24 22:58 UTC, ajkr requested changes
Actually can you also disable prefixpercent and any other iteration together with it? I don't think iteration grabs the key locks and suspect that's the root cause of the "Corrupted memtable entry" errors

2024-04-25 17:05 UTC, hx235 commented
> Actually can you also disable prefixpercent and any other iteration together with it? I don't think iteration grabs the key locks and suspect that's the root cause of the "Corrupted memtable entry" errors

Fixed the prefixpercent. Iteration percent was already disabled before.

2024-04-25 18:27 UTC, ajkr approved these changes

2024-04-25 21:11 UTC, closed without merging