Native support for incremental restore
facebook/rocksdb pull request #13239
Opened 2024-12-20 09:40 UTC by mszeszko-meta

### Summary

As advertised, with this change we are adding native library support for incremental restores. When designing the solution we decided to follow 'tiered' approach where users can pick one of the three predefined, and for now, mutually exclusive restore modes (`kKeepLatestDbSessionIdFiles`, `kVerifyChecksum` and `kPurgeAllFiles` [default]) - trading CPU / operational velocity for the degree of certainty that their existing destination db files indeed match selected backup files contents. New mode option is exposed via existing `RestoreOptions` configuration, which by this time has been already well-baked into our APIs. Restore engine will consume this configuration and infer which of the existing destination db files are 'in policy' to be retained during restore.

### Motivation

This work is motivated by internal customer who is running write-heavy, 1M+ QPS service and is using RocksDB restore functionality to scale up their fleet. Given already organically high QPS on their end, additional traffic from restores as-is today is causing prolonged spikes which lead the service to hit BLOB storage quotas, which finally results in slowing down the pace of the scaling. Please see [T206217267](https://www.internalfb.com/intern/tasks/?t=206217267) for more.

### Impact
The expected impact of this work is dual: 1) reducing the library footprint on BLOB storage quotas, 2) speeding up the scale up procedure. After landing this, we should follow up with the customers on observed gains to attribute #s to above predictions.

### Technical nuances

1. According to prior investigations, the risk of collisions on [file #, db session id, file size] metadata triplets is low enough to the point that we can confidently use it to uniquely describe the file and its' *perceived* contents, which is the rationale behind the `kKeepLatestDbSessionIdFiles` mode. To find more about the risks / tradeoffs for using this mode, please check the related comment in `backup_engine.cc`.
2. `kVerifyChecksum` mode requires a full blob / SST file scan (assuming backup file has its' `checksum_hex` metadata set appropriately, if not additional file scan for backup file). While it saves us on write IOs (if checksums match), it's still fairly complex and potentially CPU intensive operation.
3. We're extending the `WorkItemType` enum introduced in https://github.com/facebook/rocksdb/pull/13228 to accommodate a new simple request to `ComputeChecksum`, which will enable us to run 2) concurrently.
4. Note that it's necessary to compute the checksum on the restored file if corresponding backup file and existing destination db file checksums didn't match.

### Test plan

1. Manually testing using debugger: ✅ 
2. Automated tests: 🚧

2025-01-13 19:45 UTC, pdillinger requested changes
Looking good, except for compatibility with the obscure "excluded files" feature. I have a bit more to review, but sending this feedback ASAP.

2025-01-13 19:45 UTC, pdillinger commented on include/rocksdb/utilities/backup_engine.h
> +  explicit RestoreOptions(bool _keep_log_files = false,
Nits:

I'm not a fan of using positional parameters to initialize Options structs, at least when ambiguous types like `bool` are involved. If `RestoreMode` is an enum class, we could add an alternate constructor taking only a mode and mark in a comment that the bool parameter constructor as DEPRECATED.

I'm also not a fan of indicating the default in a comment, vs. assigning the default inline with the declaration, which eliminates the risk of inconsistency.

2025-01-13 19:45 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +                 static_cast<unsigned long>(files_to_keep.size()));
Should be able to use `%zu` to avoid the cast

2025-01-13 19:45 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +      const std::unique_ptr<BackupMeta>& backup, const std::string& dir,
Can't `backup` just be `const BackupMeta&`?  (Though this parameter might change entirely based on another comment.)

2025-01-13 19:45 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +                     "Existing file '%s' is retained for restore.", f.c_str());
👍

2025-01-13 19:45 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +      // This file is already in the destination directory.
I would expand this comment to make a quick argument that there's no mismatch (e.g. type of file or expected size) between what is skipped here and what was detected in `InferDBFilesToRetainInRestore`. Both are based on `BackupMeta::GetFiles()`.

At first glance, it could seem like a "weak point" where we're only using file numbers to communicate / validate, but really `files_to_keep` is just identifying a subset of `BackupMeta::GetFiles()` (and maybe `GetExcludedFiles()`).

2025-01-13 19:45 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +  InferDBFilesToRetainInRestore(backup, db_dir, options.mode, files_to_keep);
I believe that in order to support the combination of incremental restore and the somewhat obscure (but internally requested) "excluded files" feature (`exclude_files_callback`), we need to re-arrange so that we construct `restore_file_infos`, then use that in calling `InferDBFilesToRetainInRestore()`, and then do the DeleteChildren work.

2025-01-13 20:53 UTC, mszeszko-meta commented on include/rocksdb/utilities/backup_engine.h
> +  explicit RestoreOptions(bool _keep_log_files = false,
> If RestoreMode is an enum class, we could add an alternate constructor taking only a mode and mark in a comment that the bool parameter constructor as DEPRECATED.

To clarify Peter, do you suggest we should not support the `keep_log_files` option at all? Or this is just related to technicals of how to best expose the control of `keep_log_files` knob to the users?

2025-01-13 20:59 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +  InferDBFilesToRetainInRestore(backup, db_dir, options.mode, files_to_keep);
Would the primary driver for this order of operations be optimization (ex. making sure we do not attempt to compute checksum [potentially long] operation on a file that was explicitly opted-out of a backup set) or correctness?

// Today excluded files are not accounted for in `DeleteChildren`

2025-01-13 21:32 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +      // This file is already in the destination directory.
Good point!

2025-01-13 22:18 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +      // Unlike checksum_hex and size, backup db_session_id and db_id values
I was envisioning that we would not need the extra query of the backup file data because we could rely on whether the file in the target DB has metadata that generates the same full "shared" name of the backup file, for some `ShareFilesNaming` that includes `kUseDbSessionId`. When taking incremental backups, we assume this comparison of "shared" names is sufficient to distinguish distinct files, so it should suffice for incremental restore also (assuming we believe the target DB is healthy, not corrupt).

2025-01-13 22:36 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +      Log(options_.info_log, "Couldn't parse existing file name: '%s'",
True. Especially given that we're not holding a tight grip over the underlying filesystem and users can store arbitrary content in arbitrary volumes in here. Will skip.

2025-01-13 22:41 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +          "File type mismatch between backup and dest file system!"
This was intended to short circuit into 'do not retain' existing db file if names are same but extensions differ - as it's clearly different entity. I agree that messaging 'as-is' might suggest that something in the backup file is malformed - but that was not the intent. I'll polish the messaging.

2025-01-13 23:08 UTC, pdillinger commented on include/rocksdb/utilities/backup_engine.h
> +  explicit RestoreOptions(bool _keep_log_files = false,
Just trying to work toward https://github.com/facebook/rocksdb/issues/13293 (just filed). Also OK to leave the work to that broader task.

2025-01-13 23:11 UTC, mszeszko-meta commented on include/rocksdb/utilities/backup_engine.h
> +  explicit RestoreOptions(bool _keep_log_files = false,
I'll leave the annotation: `ISSUE(https://github.com/facebook/rocksdb/issues/13293)`.

2025-01-13 23:30 UTC, pdillinger commented on utilities/backup/backup_engine_test.cc
> +  std::vector<std::string> always_copyable_files = {
Explicit list of files like this is fragile to changes in DB operations that might change the order or when we allocate new file numbers. You might have taken inspiration from existing testings in this same test file, but those are subtly either (a) constructing a dummy DB from a set of file names and looking at how they are handled, or (b) injecting extra files into the backup dir to be cleaned up. Do you think we can avoid this?

2025-01-14 00:04 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +      Log(options_.info_log, "Couldn't parse existing file name: '%s'",
Same for `type != kTableFile && type != kBlobFile` trace below.

2025-01-14 00:28 UTC, mszeszko-meta commented on include/rocksdb/utilities/backup_engine.h
> +enum RestoreMode : uint32_t {
Kept `enum`, moved under `RestoreOptions`.

2025-01-14 00:31 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +      // This file is already in the destination directory.
Adjusted the comment. In the next commit (targeting excluded files feature compatibility) message will include appropriate `excluded files` commentary.

2025-01-14 18:41 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +      // Unlike checksum_hex and size, backup db_session_id and db_id values
Main motivation was to treat metadata persisted in the footer as the only source of truth. Given your explanation from above, Peter, I think we can confidently refactor it to reduce queries to backup files. I will address this in the next iteration.

2025-01-14 22:29 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +  InferDBFilesToRetainInRestore(backup, db_dir, options.mode, files_to_keep);
Re-arranged the order. As a result, we'd expect to retain the existing db files that have corresponding backup file info pointing to excluded directories (potentially outside of backup directory). @pdillinger, let me know if compatibility with excluded files looks good to you. I'm keeping this comment as 'open' since I plan to add some more test coverage for the excluded files.

2025-01-16 18:27 UTC, pdillinger commented on utilities/backup/backup_engine.cc
> +  if (unowned_sst_backups.size() > 0) {
Can we avoid this extra block of code while handling this unusual case? Perhaps worth chatting about

2025-01-17 02:26 UTC, mszeszko-meta commented on utilities/backup/backup_engine.cc
> +  static bool ParseDbSessionIdAndSizeFromFile(const std::string& path,
Refactored. To keep it simple we'll only make incremental restores applicable to `kUseDbSessionId` + `kFlagIncludeFileSize`.

2025-01-18 00:20 UTC, pdillinger approved these changes
Awesome, thanks!

2025-01-18 00:20 UTC, pdillinger commented on utilities/backup/backup_engine_test.cc
> +                           RestoreOptions::Mode::kVerifyChecksum}) {
I would argue we should include the kPurgeAll mode here as a proper "control" (we aren't unexpectedly doing incremental things under that default mode)

2025-01-18 00:47 UTC, mszeszko-meta commented on utilities/backup/backup_engine_test.cc
> +                           RestoreOptions::Mode::kVerifyChecksum}) {
Done!

2025-01-18 05:33 UTC, closed without merging