Expose Cache statistics in JNI
facebook/rocksdb pull request #6954
Opened 2020-06-08 08:51 UTC by koldat

This PR exposes basic getters of LRU cache in Java. It allows us to do better monitoring.
```
long getCapacity() throws RocksDBException;
long getUsage() throws RocksDBException;
long getHighPriorityPoolUsage() throws RocksDBException;
long getPinnedUsage() throws RocksDBException;
long getEntries() throws RocksDBException;
```

2020-06-08 08:52 UTC, koldat commented
@adamretter , please take a look

2020-06-10 09:51 UTC, adamretter requested changes
LGTM in general. We just need to check about extending the C++ public API...

2020-06-10 09:51 UTC, adamretter commented on java/rocksjni/lru_cache.cc
> +jlong Java_org_rocksdb_Cache_getCapacity(JNIEnv* /*env*/, jobject /*jobj*/,
Please just omit the commented out parameter names.

2020-06-10 09:51 UTC, adamretter commented on java/src/main/java/org/rocksdb/Cache.java
> +  private native long getCapacity(final long handle) throws RocksDBException;
It looks to me like these methods will never throw `RocksDBException`. If that is the case, perhaps remove the exceptions.

2020-06-10 09:51 UTC, adamretter commented on java/src/test/java/org/rocksdb/LRUCacheTest.java
> +  public void newLRUCache() throws RocksDBException {
Will an exception be needed?

2020-06-10 09:51 UTC, adamretter commented on include/rocksdb/cache.h
> +  // returns the memory size for the high priority entries residing in the
Thanks @koldat, in general this looks good to me.

However, this PR is a bit more than just exposing things to RocksJava... I note you are also adding new C++ API methods to expose values in the C++ API. I think therefore we should just check with @siying that he is happy for these values to be added to the public API...

2020-06-10 13:17 UTC, mrambacher reviewed
I can see the utility of the "GetEntries" counter in the cache but question the GetHighPriorityUsage.  If you are using a ClockCache (which I am not sure you have no way of knowing), the result would be 0, which may be misleading.

I also would question if this is the way you really want to collect stats about the cache.  To collect all of those statistics, you would be making multiple JNI calls.  Each JNI call is going to do a bunch of mutex locks.  A better solution might be to propose the introduction of some sort of cache->GetStats() call in C++ that fills in some stats structure (map<string, size_t>?) and pass that back and forth.

Of course, that is probably outside of the scope of work you are asking for.

Finally, there should probably be some C++ tests for the new APIs somewhere.

2020-07-22 10:54 UTC, koldat commented
@siying can you please comment on this API? I can make it cleaner. The thing is that I have found serious performance issue just because of this simple metric. What happened?

- I am using limited max_open_files so I want to use cache. So I use LRU cache + pin_top_level_index_and_filter(true).
- I am using two level index so that pinned data should be tiny
- After long time I see that pinned blocks are just growing so that cache stops to be useful at all (valid blocks does not fit).

Without this metric I was blind. There was no errors, the application performance just dropped a lot. As I was expecting something weird with cache I have added at least this way of doing that.

Now the question is if sum of all top level indices size was really 4GB or if these is some "pinned" leak. Anyway after I stopped pinning it helped a lot with no slowdown. I am just trying to say how important it is.

![image](https://user-images.githubusercontent.com/16866502/88168037-17478300-cc1a-11ea-8622-771a78cf9a45.png)

![image](https://user-images.githubusercontent.com/16866502/88168137-465df480-cc1a-11ea-96a6-1c9c297d4d57.png)

![image](https://user-images.githubusercontent.com/16866502/88168240-6e4d5800-cc1a-11ea-91c2-a505a74eae13.png)

2020-10-02 17:35 UTC, siying reviewed
Sorry I didn't see the notification.

2020-10-02 17:35 UTC, siying commented on include/rocksdb/cache.h
> +  virtual size_t GetHighPriorityPoolUsage() const = 0;
This function looks good to me.

2020-10-02 17:35 UTC, siying commented on include/rocksdb/cache.h
> +  virtual size_t GetEntries() const = 0;
I'm not sure this information is necessarily available in the cache. I'm not even sure the value returned by LRU cache and clock cache is accurate, and the information might be unavailable from another implementation. Do you really need this stat?

2026-04-26 13:25 UTC, closed without merging