Unified the file header in java api
facebook/rocksdb pull request #7542
Opened 2020-10-13 05:31 UTC by darionyaphet

I don't know why there are two different kind of file header in java api. IF it's necessary I will update the other file

2020-10-13 10:39 UTC, adamretter approved these changes

2020-10-14 16:13 UTC, pdillinger commented on java/src/main/java/org/rocksdb/VectorMemTableConfig.java
> +// Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.// Copyright (c) 2011-present, Facebook, Inc.  All rights reserved.
Oops

2020-10-14 16:17 UTC, pdillinger requested changes
Our open source team actually prefers the dateless header now. See e.g. util/math128.h

2020-10-15 02:22 UTC, darionyaphet commented
> Our open source team actually prefers the dateless header now. See e.g. util/math128.h

you mean `Copyright (c) 2011-present, Facebook, Inc.` have discard ? And currently we are using 

```
// Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
```

as our file header ?

2020-10-15 15:16 UTC, pdillinger commented
> // Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.

No year is now preferred, so certainly don't replace this with a copyright line with years.

2020-10-15 15:28 UTC, darionyaphet commented
> > // Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
> 
> No year is now preferred, so certainly don't replace this with a copyright line with years.

OK I will close this one thanks for your help ~

2020-10-15 15:28 UTC, closed without merging