Add more tests to ASSERT_STATUS_CHECKED
facebook/rocksdb pull request #7679
Opened 2020-11-16 15:55 UTC by adamretter

Further tests with ASSERT_STATUS_CHECKED

2020-11-16 16:22 UTC, mrambacher approved these changes
LGTM!

2020-11-16 19:34 UTC, pdillinger requested changes
ASC check failed in CI (both Travis & CircleCI - I didn't dig into details)

2020-11-16 19:58 UTC, adamretter commented
@mrambacher @pdillinger There is one failing test now in `db_merge_operator_test.cc` which is: ` MergeOperatorPinningTest/MergeOperatorPinningTest.TailingIterator/0`.

The problem is that this code:
```C++
    ReadOptions ro;
    ro.tailing = true;
    Iterator* iter = db_->NewIterator(ro);
```

Creates an `DBIter` which wraps a `ForwardIterator`, the implementation of `DBIter::status()` is then:

```
Status status() const override {
    if (status_.ok()) {
      return iter_.status();
    } else {
      assert(!valid_);
      return status_;
    }
  }
```

The problem in the test is that it is impossible to call `ASSERT_OK` on the `status_` field of `DBIter`.
I could do with some advice on how best to access the internal private state of `DBIter` from that test please...

2020-11-16 22:10 UTC, mrambacher commented
When the test fails, is iter_status() ok?  I think the preferred way of doing this would be in the Iterator constructor to call PermitUncheckedError on the status value.

2020-11-16 22:44 UTC, adamretter commented
@mrambacher yes, the status is OK.

So... I think U would need to do that for the status of both the wrapped `ForwardIterator` and the outer `DBIter`, as I can't rely on the status of the DBIter being OK. Does that sound reasonable still? Or is it better to expose some internal state to just the test... through an internal API only method, or some sort of friend class?

2020-12-02 16:51 UTC, mrambacher approved these changes
LGTM, with the moving of the PermitUncheckedError into the constructor...

2020-12-02 16:51 UTC, mrambacher commented on db/db_iterator_test.cc
>    ASSERT_TRUE(iter->Valid());
Should there also be a check for iter->status being OK prior to the reset?

2020-12-02 16:51 UTC, mrambacher commented on db/forward_iterator.cc
> +
The problem is that status_ is never set (or checked) by this test.  A better solution is to put the PermitUncheckedError into the constructor.  That way, if the status is ever set and not checked by another test, they would see the assert.

I believe that is safe to do (and probably the right thing) without the associated comment.

2020-12-07 18:09 UTC, pdillinger commented
I did a merge with master and got many ASC failures. I should be available to try to land this quickly once it is back to working again.

2020-12-07 18:10 UTC, pdillinger requested changes
I did a merge with master and got many ASC failures.

2020-12-07 18:22 UTC, adamretter commented
@pdillinger So was this introduced by merging onto master? What should I do next? Should I rebase this onto master and fix any resulting ASC fails?

2020-12-07 19:29 UTC, pdillinger commented
> @pdillinger So was this introduced by merging onto master? What should I do next? Should I rebase this onto master and fix any resulting ASC fails?

I don't know, but I don't attempt to land anything touching this many files with a merge base more than a few days old. (This one is two weeks old.) And it seems I can't push to this branch to run CI on the merge, so I'm trusting my local runs (both clang and gcc) until I see otherwise.

2020-12-08 10:00 UTC, adamretter commented
@pdillinger I rebased this onto master. I only saw one new failing ASC, so I fixed that. Is the PR good to go now?

2020-12-08 18:04 UTC, pdillinger commented
Thanks. I was running 'make check' which runs tests presumed to be broken, but I stand by my heuristic merge age limits. ;)

2020-12-08 23:55 UTC, closed without merging