Fix build on FreeBSD/powerpc64(le)
facebook/rocksdb pull request #7732
Opened 2020-12-02 00:38 UTC by pkubaj

To build on FreeBSD, arch_ppc_probe needs to be adapted to FreeBSD.

Since FreeBSD uses elf_aux_info as an getauxval equivalent, use it and include necessary headers:
- machine/cpu.h for PPC_FEATURE2_HAS_VEC_CRYPTO,
- sys/auxv.h for elf_aux_info,
- sys/elf_common.h for AT_HWCAP2.

elf_aux_info isn't checked for being available, because it's available since FreeBSD 12.0. rocksdb assumes using Clang on FreeBSD, but powerpc* platforms switch to Clang only since 13.0.

This patch makes rocksdb build on FreeBSD on powerpc64 and powerpc64le platforms.

2020-12-07 14:30 UTC, adamretter commented
@pkubaj I just ran this against Linux of ppc64le to make sure that was still fine too. It looks good.

Thanks for your contribution.

@pdillinger I think this is ready to merge.

2020-12-07 16:32 UTC, pdillinger requested changes

2020-12-07 16:32 UTC, pdillinger commented on util/crc32c.cc
> +#include <sys/elf_common.h>
Please move #include outside of namespace

2020-12-08 17:11 UTC, pdillinger approved these changes
Thanks for the contribution!

2020-12-08 23:32 UTC, closed without merging