Fix for a false corruption error during point-in-time WAL recovery.
facebook/rocksdb pull request #7859
Opened 2021-01-13 02:21 UTC by deepakojha123

The error is thrown when last-flushed-WAL file for any CF is more
recent than corrupted WAL file. The fix is to skip this error if
all WAL files more recent than the corrupted WAL file are empty.

Fixes issue #7784.

2021-01-21 23:47 UTC, deepakojha123 commented
@ajkr, @anand1976 Any inputs/comments on this change?

2021-01-22 06:34 UTC, ajkr reviewed
Thanks for the PR and sorry for the delay!

2021-01-22 06:34 UTC, ajkr commented on db/db_impl/db_impl_open.cc
> +          ++ii;
Sorry it isn't obvious to me why we increment `ii` here. I thought we executed this logic only for WALs after the corrupted WAL, so we are already past it. Also it seems to execute for all non-empty WALs following the first corrupted WAL, in which case could this scenario increase `corrupted_wal_number` too far?

- WAL 1 is corrupt
- WAL 2 is empty
- WAL 3 is empty
- WAL 4 is non-empty
- WAL 5 is empty

I am not sure what prevents `corrupted_wal_number` from reaching 5, but feel it should be 3.

2021-01-22 06:46 UTC, ajkr requested changes
I think the logic would be correct if it's moved to the outer loop, around where we set `stop_replay_for_corruption = true;`. The only other thing is we need to make sure `ii` doesn't advance too far. Maybe keep `ii` trailing one behind the file whose emptiness we're checking.

2021-01-24 02:08 UTC, deepakojha123 commented
@ajkr  Thanks for the review! Agreed the logic should be where we set stop_replay_for_corruption = true. As for corrupted_wal_number going too far: the loop breaks when it finds first non-empty WAL so ii should be set back to last empty WAL which was missing in my previous commit. I have a new commit, please see if this looks better?

2021-01-24 05:11 UTC, deepakojha123 commented
db_wal_test failed with this change and upon debugging I think pointing corrupted_wal_number to next empty wal file has one hole, if a CF flush had happened with some keys from the original corrupted_wal_number we won't catch it?

[ RUN      ] DBWALTest.kPointInTimeRecoveryCFConsistency
db/db_wal_test.cc:1311: Failure
Value of: (TryReopenWithColumnFamilies({"default", "one", "two"}, options)).ok()
  Actual: true
Expected: false

2021-01-28 01:58 UTC, ajkr commented
> one hole, if a CF flush had happened with some keys from the original corrupted_wal_number we won't catch it?

This sounds right. Sorry I should have thought through it more carefully. The zero-byte WAL doesn't seem like the root cause (if you still have the original DB, does `Open()` still fail with the zero-byte WAL removed?). It seems more likely an SST actually could have contained data newer than the checksum error that was detected. In that case it'd be a valid failure.

2021-01-29 02:01 UTC, deepakojha123 commented
@ajkr Unfortunately I don't have the original DB. Digging further, looks like 6.4.6 has a bug which was fixed in PR #5856. The condition is precisely what we are hitting: a point-in-time recovery with a corrupted wal file and a crash during recovery after flushing some CFs. Now the flushed CFs moved past the corrupted wal while remaining CFs still behind. Next Open will hit the corruption error. The fix is to update the Manifest atomically for all CFs after the flush.

2021-02-01 23:37 UTC, deepakojha123 commented
I think we can drop this PR given that issue #7784 seems to be already fixed in PR #5856.

2021-02-01 23:38 UTC, closed without merging