reimplement print single sst meta when dump manifest
facebook/rocksdb pull request #8557
Opened 2021-07-19 07:40 UTC by hunterlxt

original PR https://github.com/facebook/rocksdb/pull/6716

Add --sst_file_number field for manifest_dump command to print the specified sst file meta. By the way, add key order check for sst_dump.

Usage:
$ ./ldb --db=/data3/zbk/kv4/deploy/data/db --hex manifest_dump --sst_file_number=63
```
--------------- Column family "write"  (ID 2) --------------
63:132906243[3555338 .. 3555338]['7A311B40EFCC2CB4C5911ECF3937D728DED26AE53FA5E61BE04F23F2BE54EACC73' seq:3555
338, type:1 .. '7A313030302E25CD5F57252E' seq:3555338, type:1] oldest_ancester_time:0 at level 0
```

Signed-off-by: Xintao <hunterlxt@live.com>

2021-07-19 07:56 UTC, hunterlxt commented
@pdillinger PTAL

2021-07-19 17:25 UTC, riversand963 requested changes
Thanks @hunterlxt for bringing up the issue.
Can the same functionality be achieved without adding more options to `ldb` which already has a lot of options? Will using `grep` after the original result of `ldb` work for your use case?

2021-07-19 17:25 UTC, riversand963 commented on db/version_edit_handler.cc
> +  std::vector<FileMetaData*>* files = new std::vector<FileMetaData*>;
Where is `files` free'ed?

2021-07-19 17:25 UTC, riversand963 commented on db/version_edit_handler.cc
> +    VersionEditHandler::CheckIterationResult(reader, s, files);
Still trying to understand more about this PR, but at the moment, I am not fully convinced of the necessity of a separate `CheckIterationResult`.

2021-11-02 00:00 UTC, riversand963 commented
I believe the same functionality can be achieved in another, simpler way. Closing.

2021-11-02 00:00 UTC, closed without merging

2023-03-29 03:11 UTC, cscetbon commented
@riversand963 was it implemented using a simpler way like you said ? I can't find it