Add periodic_compaction_seconds option to RocksJava
facebook/rocksdb pull request #8579
Opened 2021-07-23 11:15 UTC by zhmaeff

Fixes #8578

2021-07-23 12:18 UTC, zhmaeff commented
Hi @adamretter could you please review?

2021-07-23 17:28 UTC, adamretter requested changes
LGTM just some very minor stuff around `final` parameters.

2021-07-23 17:28 UTC, adamretter commented on java/src/main/java/org/rocksdb/ColumnFamilyOptions.java
> +  public ColumnFamilyOptions setPeriodicCompactionSeconds(long periodicCompactionSeconds) {
Please mark the parameter as `final`.

2021-07-23 17:28 UTC, adamretter commented on java/src/main/java/org/rocksdb/MutableColumnFamilyOptions.java
> +    public MutableColumnFamilyOptionsBuilder setPeriodicCompactionSeconds(long periodicCompactionSeconds) {
Please mark parameter as `final`.

2021-07-23 17:28 UTC, adamretter commented on java/src/main/java/org/rocksdb/Options.java
> +  public Options setPeriodicCompactionSeconds(long periodicCompactionSeconds) {
Please mark parameter as `final`.

2021-07-24 07:54 UTC, zhmaeff commented
> LGTM just some very minor stuff around `final` parameters.

@adamretter Thank you for a quick review! Fixed!

2021-07-24 14:17 UTC, adamretter approved these changes

2021-07-24 18:36 UTC, zhmaeff commented
Hi @mrambacher ! I see some tests are failing https://github.com/facebook/rocksdb/pull/8579/checks?check_run_id=3150162628 , is it related to my code? Is it a blocker for this PR?

2021-07-26 00:22 UTC, mrambacher commented
> Hi @mrambacher ! I see some tests are failing https://github.com/facebook/rocksdb/pull/8579/checks?check_run_id=3150162628 , is it related to my code? Is it a blocker for this PR?

Can you update your branch to the latest?  I think everything should be okay after that.

2021-07-26 08:09 UTC, zhmaeff commented
2 builds are failing because of 
> "Download snap "cmake" (912) from channel "beta" (received an unexpected http response code (503) when trying to download ...snap"
@mrambacher could you pls rerun them and start internal FB checks?

2021-07-26 13:24 UTC, mrambacher commented
Can you please run "make format" and re-push?

2021-07-27 00:33 UTC, closed without merging