Add NewMetaDataIterator method
facebook/rocksdb pull request #8692
Opened 2021-08-23 18:21 UTC by mrambacher

Fixes a problem where the iterator for metadata was being treated as a non-user key when in fact it was a user key.  This led to a problem where the property keys could not be searched for correctly.

The main exposure of this problem was that the HashIndexReader could not get the "prefixes" property correctly, resulting in the failure of retrieval/creation of the BlockPrefixIndex.

Added BlockBasedTableTest.SeekMetaBlocks test to validate this condition.

Fixing this condition exposed two other tests (SeekWithPrefixLongerThanKey, MultiGetPrefixFilter) that passed incorrectly previously and now failed.  Updated those two tests to pass.  Not sure if the tests are functionally correct/still appropriate, but made them pass...

2021-08-23 18:21 UTC, mrambacher commented
Fixes #8673

2021-12-15 00:42 UTC, mrambacher commented on table/block_based/block.cc
> +  ret_iter->raw_key_.SetIsUserKey(true);
There are other differences between a DataBlockIter and a MetaBlockIter:
- MetaBlockIter always use BytewiseComparator; DatBlockIter uses one associated with the table;
- MetaBlockIter uses non-assert functions for parsing keys (CheckAndDecodeEntry) whereas DataBlockIter asserts (DecodeEntry)
- MetaBlockIter will not change read amplification and is not reflected in the Statistics

The naming of "MetaBlockIter" was chosen as it is used to read from a variable called "metablock_index" in a method called "FindMetaBlock".  

If you prefer a different name, feel free to suggest one.

2021-12-15 19:55 UTC, pdillinger reviewed
This needs performance testing. Changing templates (static polymorphism) to virtual functions (dynamic polymorphism) is probably a regression in this hot code, possibly also heap allocating objects that can go on the stack.

(Doesn't have to be here and now...) I think we're more likely to see net improvement if we change from an "iterator" interface to a "visitor" interface for meta blocks. Metaindex and properties should be parsed once on read, never on the fly. I don't know how much code that would involve, but naively it would seem less entangled with data and index block iteration.

2021-12-15 19:55 UTC, pdillinger commented on table/block_based/block.cc
>    // Delta encoding is used if `shared` != 0.
Update comment

2021-12-15 20:04 UTC, mrambacher commented
> This needs performance testing. Changing templates (static polymorphism) to virtual functions (dynamic polymorphism) is probably a regression in this hot code, possibly also heap allocating objects that can go on the stack.
> 
> (Doesn't have to be here and now...) I think we're more likely to see net improvement if we change from an "iterator" interface to a "visitor" interface for meta blocks. Metaindex and properties should be parsed once on read, never on the fly. I don't know how much code that would involve, but naively it would seem less entangled with data and index block iteration.

@pdillinger I will run some performance tests but the Iterator class already has virtual functions.  This PR is not introducing any polymorphism.

2021-12-15 21:03 UTC, pdillinger commented on table/block_based/block.cc
> +    const char* key_ptr = DecodeKV(data_ + region_offset, data_ + restarts_,
DecodeKeyFunc -> DecodeKV (static -> dynamic polymorphism)

2021-12-16 18:11 UTC, mrambacher commented
> This needs performance testing. Changing templates (static polymorphism) to virtual functions (dynamic polymorphism) is probably a regression in this hot code, possibly also heap allocating objects that can go on the stack.
> 
> (Doesn't have to be here and now...) I think we're more likely to see net improvement if we change from an "iterator" interface to a "visitor" interface for meta blocks. Metaindex and properties should be parsed once on read, never on the fly. I don't know how much code that would involve, but naively it would seem less entangled with data and index block iteration.

I ran the following command on both main and on this PR:
TEST_TMPDIR=/dev/shm ./db_bench -benchmarks=filluniquerandom,compact -target_file_size_base=1048576 -compression_type=none
TEST_TMPDIR=/dev/shm ./db_bench -readonly=1 -use_existing_db=1 -benchmarks=seekrandom -seek_nexts=1000 -target_file_size_base=1048576 -cache_size=0 -duration=30

Results for main:
seekrandom   :     164.420 micros/op 6081 ops/sec;  672.5 MB/s (182999 of 182999 found)
seekrandom   :     165.281 micros/op 6050 ops/sec;  669.0 MB/s (181999 of 181999 found)
seekrandom   :     168.022 micros/op 5951 ops/sec;  658.1 MB/s (178999 of 178999 found)

Results for this PR:
seekrandom   :     165.602 micros/op 6038 ops/sec;  667.7 MB/s (181999 of 181999 found)
seekrandom   :     165.443 micros/op 6044 ops/sec;  668.3 MB/s (181999 of 181999 found)
seekrandom   :     169.142 micros/op 5912 ops/sec;  653.7 MB/s (177999 of 177999 found)

2021-12-17 00:57 UTC, pdillinger approved these changes
LGTM. I ran my own perf test as in #9126 and if anything, this is slightly faster than baseline, 122474 vs. 121924 ops/sec.

2021-12-17 00:59 UTC, pdillinger commented
Note: FB test coverage indicates MetaBlockIter::SeekForPrevImpl is not covered.

2021-12-17 01:40 UTC, mrambacher commented
> Note: FB test coverage indicates MetaBlockIter::SeekForPrevImpl is not covered.

I am not surprised this is not covered.  The method is required by the signature but everything that uses MetaBlocks either does a seek or scan.  I can delete the contents if you wish and have it assert/fail.

2021-12-17 05:14 UTC, pdillinger commented
> I am not surprised this is not covered. The method is required by the signature but everything that uses MetaBlocks either does a seek or scan. I can delete the contents if you wish and have it assert/fail.

I don't have a specific preference

2021-12-17 20:23 UTC, riversand963 commented on table/block_based/block.h
> +  virtual void PrevImpl() override;
https://stackoverflow.com/questions/39932391/should-i-use-virtual-override-or-both-keywords
Please remove 'virtual'.

2021-12-17 21:37 UTC, riversand963 requested changes
I am not expert at block-related code, and rely on the author's benchmarking to demonstrate no regression on the hot path.

We follow https://google.github.io/styleguide/cppguide.html#Local_Variables, and as a good practice, we should always initialize variables. Relying on a subsequent function call to always set the value sounds risky.

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +    bool shared;
Init

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.h
> +class MetaBlockIter final : public BlockIter<Slice> {
Please add some comment describing why we need this class.

2021-12-17 21:37 UTC, riversand963 commented on db/db_with_timestamp_basic_test.cc
> +  static int kMinKeyLen = 3;
Nit: can be constexpr

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +  bool is_shared;
Nit: better to init

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +  bool is_shared;
better to init

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +  bool is_shared;
better to init

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +  bool is_shared;
Nit: init

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +  bool is_shared;
Nit: init

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.cc
> +    *value_length = 0;
Nit: our internal linter may complain about nullptr ref. So assert(value_length).

2021-12-17 21:37 UTC, riversand963 commented on table/block_based/block.h
> +    raw_key_.SetIsUserKey(true);
Given this is the core fix, maybe a line or two of explanation helps emphasizing the significance.

2021-12-17 23:01 UTC, riversand963 approved these changes
LGTM. Thanks @mrambacher for the fix.

2021-12-21 19:32 UTC, closed without merging