MemTableList::TrimHistory now use allocated bytes
facebook/rocksdb pull request #9020
Opened 2021-10-12 10:00 UTC by lgqss

Fix a bug when both max_write_buffer_size_to_maintain and max_write_buffer_number_to_maintain are 0. 
The bug was introduced in 6.5.0 and  #5022.
Fix #8371

2021-11-15 19:38 UTC, ajkr commented
Thanks I agree there is a problem from the log lines. Looking at:

```
max_write_buffer_size_to_maintain_:805306368 max_write_buffer_number_to_maintain_:0 memlist_history_.size:88 ApproximateMemoryUsageExcludingLast:6908072
```

It is using `arena_block_size * memlist_history_.size() = 16MB * 88 = 1408MB` memory to maintain < 7MB of write history. And that'll keep growing since write history limit is `max_write_buffer_size_to_maintain = 768MB`.

One thing that should help is upgrading to 6.21 or higher. #7907 reduced the max arena_block_size to 1MB.

2021-11-15 20:17 UTC, ajkr commented
I wonder if it would work for us to rewrite memtables with large wastage during flush before they become history. For example when `ApproximateMemoryUsage() << 1MB` we could create a new memtable for the history with allocation size `ApproximateMemoryUsage()` and copy into that.

But it's a non-trivial change. If you are able to avoid tiny memtables and/or disproportionately large arena_block_size it might be good enough. You could also try max_write_buffer_number_to_maintain as you mentioned, with the downside that the actual amount of write history will be less predictable.

2021-11-19 04:05 UTC, lgqss commented
Should we use arena_block_size instead of ApproximateMemoryUsage() if ApproximateMemoryUsage() < arena_block_size.

2021-11-19 19:02 UTC, ajkr commented
> Could we use arena_block_size instead of ApproximateMemoryUsage() if ApproximateMemoryUsage() < arena_block_size? When ApproximateMemoryUsage() >= arena_block_size, same the as current code. When ApproximateMemoryUsage() < arena_block_size, we can keep (max_write_buffer_number_to_maintain/arena_block_size) memtables . It's enough.

I think we should consider allocated bytes, yes. But we should list it under "Behavior Changes" in HISTORY.md. Also can we always use allocated bytes, for example, by introducing a MemTable::MemoryAllocatedBytes() function and using that instead? We could use this formula to implement it. https://github.com/facebook/rocksdb/blob/12117b26a359dc4e9649994b96991acb0720b3ff/db/memtable.cc#L164-L166

2021-11-24 12:21 UTC, lgqss commented
> Also can we always use allocated bytes
I think it's ok in 1MB arena_block_size. 
If users set a large value(e.g. 16MB) , I don't quite know what the impact is.

2021-11-29 21:02 UTC, ajkr requested changes

2021-11-29 21:02 UTC, ajkr commented on db/memtable_list.cc
> +  // m->ApproximateMemoryUsage() is added in ApproximateMemoryUsageExcludingLast
Good point.

2021-12-01 09:51 UTC, lgqss commented on HISTORY.md
> +* MemTableListVersion::ApproximateMemoryUsageExcludingLast now use allocated bytes(arena_block_size) when history memtable's memory_usgage < arena_block_size. This change only affects immutable memta
I think it's confused for others if we just use allocated bytes in first arena block.
So I think we need always use allocated bytes as you suggested

2021-12-01 13:43 UTC, lgqss commented on HISTORY.md
> +* MemTableListVersion::ApproximateMemoryUsageExcludingLast now use allocated bytes(arena_block_size) when history memtable's memory_usgage < arena_block_size. This change only affects immutable memta
I think it's confused for others if we just use allocated bytes in first arena block.
So I think we need always use allocated bytes as you suggested.

2021-12-01 20:12 UTC, ajkr approved these changes
Looks great, thank you very much!

2021-12-02 19:45 UTC, closed without merging