[RFC][WIP] Remove HDFS support from main repo and migrate to separate repo
facebook/rocksdb pull request #9170
Opened 2021-11-15 21:41 UTC by riversand963

This PR moves HDFS support from RocksDB repo to a separate repo. The new (temporary?) repo
in this PR serves as an example.

Java/JNI is not included yet, and needs to be done later if necessary.

The goal is to include this commit in RocksDB 7.0 release.

Reference:
https://github.com/ajkr/dedupfs by @ajkr 

Test plan:
Follow the instructions in https://github.com/riversand963/rocksdb-hdfs-env/blob/master/README.md. Build and run db_bench and db_stress.

make check

2021-11-15 21:53 UTC, riversand963 commented
@adamretter, is it possible to move HDFS-related JNI code from main repo to https://github.com/riversand963/rocksdb-hdfs-env as well?

2021-11-15 22:07 UTC, mrambacher requested changes
While I agree with most of this change, is there a reason we should move HDFS under plugins/hdfs in the main repo?  HDFS is one (of several) plugins that are currently in the source that should be moved into their own "untested" and "unsupported" place (like LUA and Rados and Cassandra).  

For those tools that currently use them, it would make it simpler if we kept the code in one place.  It would also simplify testing that we can do the right thing in building the plugins and getting the infrastructure working (regardless of if we ever actually RUN them).

2021-11-15 22:07 UTC, mrambacher commented on Makefile
> +CXXFLAGS += $(foreach plugin, $(ROCKSDB_PLUGINS), $($(plugin)_CXXFLAGS))
Shouldn't this be PLATFORM_CXXFLAGS?

2021-11-15 23:44 UTC, ajkr reviewed
The example repro should register a name matching the whole URI like "hdfs://.*" instead of "hdfs". Other than that it worked great!

We can clarify the temporary repo is meant as a starting point for whoever wants to take ownership assuming that is the intent.

2021-11-16 00:48 UTC, riversand963 commented
@mrambacher 
Just to clarify, we are not simply moving hdfs to plugins/hdfs in the main repo. We are removing hdfs support from main repo and moving it to a separate repo. Currently, it is hosted temporarily at https://github.com/riversand963/rocksdb-hdfs-env.git, and we can finalize the location or anybody can fork it. Future contribution to hdfs-specific code should not go to main repo. Only if somebody wants to build RocksDB with hdfs will they clone the repo to plugins/hdfs. We probably should do the same for all special Env/FS, e.g. rados, etc.

After removing the hdfs-specific code from main repo and ensuring there is a workaround solution as described in this PR, I currently do not have strong opinion on next step w.r.t #7949, and I don't think this PR should be blocked on a WIP feature. Even after HdfsEnv or HdfsFS and/or Env becomes Customizable, I think the approach in this PR should still work, and it does not prevent the development of #7949.

2021-11-24 18:21 UTC, ajkr reviewed
Looks like Java bindings need to be deleted too.

2021-11-24 20:56 UTC, adamretter commented
@ajkr Yes indeed, it is on my TODO list (nearish the top)

2021-11-30 00:42 UTC, riversand963 commented
Hi @adamretter,
Discussed with @ajkr offline. Is it possible to expose a `createEnvFromUri()` public Java API? If so, is it possible to get rid of the Java binding code for HDFS?

2021-11-30 03:47 UTC, darionyaphet commented
Maybe HDFS is not the only option. Would support be more optional in the future?

2021-11-30 10:29 UTC, adamretter commented
> Is it possible to expose a createEnvFromUri() public Java API? 

@riversand963 As part of HDFS support, or as something else in RocksDB?

2021-11-30 16:16 UTC, mrambacher commented
The Customizable infrastructure (e.g. XXX::CreateFromString) will work for all of the extension classes (Env is still pending).  I believe that is the interface that needs to be added to Java, for all of the Customizable classes

Having said that, I am not sure I understand how HDFS (or other plugins) can be accessed in Java unless they are built into the initial shared library, which means we will either be distributing a lot of Maven packages for the possible combinations (2 plugins means 4 packages, 3 means 8, etc) or have a means of dynamically adding them to the Java project.

2021-11-30 16:58 UTC, adamretter commented
@mrambacher The approach taken in https://github.com/riversand963/rocksdb-hdfs-env/ is to build everything from source, so I doubt we will distribute those binaries. Otherwise with that approach we would have one complete binary of RocksDB for each plugin - and then what happens if you want two plugins?!?

2021-11-30 22:00 UTC, riversand963 commented
@adamretter correct, I don't think we will distribute binaries for different combinations of RocksDB + (HDFS + RADOS).

> As part of HDFS support, or as something else in RocksDB

Something else in RocksDB as a public Java API.

2021-11-30 22:01 UTC, ajkr approved these changes
LGTM, just need to remove Java binding.

2021-12-01 00:20 UTC, riversand963 commented
Thanks @ajkr for the review! Yeah, we will merge this after Java bindings for HDFS are deleted from main repo and we have an alternative.

2021-12-01 00:21 UTC, riversand963 commented
> Maybe HDFS is not the only option. Would support be more optional in the future?

@darionyaphet Not sure if I understand. Do you mean "support for more file systems"?

2021-12-01 01:05 UTC, darionyaphet commented
> > Maybe HDFS is not the only option. Would support be more optional in the future?
> 
> @darionyaphet Not sure if I understand. Do you mean "support for more file systems"?

yep such as alluxio

2021-12-01 01:12 UTC, adamretter commented
I am happy with what you are proposing. My concern is, if somebody wants two plugins, then your design is impossible... Or did I misunderstand?

2021-12-01 05:08 UTC, riversand963 commented
@darionyaphet no, we do not have such plans at the moment.

2021-12-01 05:44 UTC, riversand963 commented
@adamretter 
> I am happy with what you are proposing. My concern is, if somebody wants two plugins, then your design is impossible... Or did I misunderstand?

I assume you are replying to my prior comment.
I am not sure I follow. Can you elaborate on why it's not possible to have two plugins? Is this something specific in Java? In this PR, I can build RocksD with both dedupfs and hdfs and running db_stress with either of them.

2021-12-01 18:32 UTC, ajkr commented
> @adamretter
> 
> > I am happy with what you are proposing. My concern is, if somebody wants two plugins, then your design is impossible... Or did I misunderstand?
> 
> I assume you are replying to my prior comment. I am not sure I follow. Can you elaborate on why it's not possible to have two plugins? Is this something specific in Java? In this PR, I can build RocksDB with both dedupfs and hdfs and run db_stress with either of them.

Right it is possible for users who build from source to include as many plugins as they want. IMO the Java release should include zero plugins. I suspect the Java release already does not include a functioning HdfsEnv since (before this PR) that required compiling with `USE_HDFS=1` and linking `-lhdfs`.

2021-12-01 19:19 UTC, riversand963 commented
@ajkr correct, current Java release does not include HDFS.

2022-01-25 04:24 UTC, closed without merging

2022-01-25 05:35 UTC, riversand963 commented
Hi @alanpaxton, I have merged this PR to main, would it be possible for you to rebase https://github.com/riversand963/rocksdb/pull/4 onto facebook/main? Thanks!
cc @adamretter