Update libs for RocksJava Static build
facebook/rocksdb pull request #9304
Opened 2021-12-16 17:58 UTC by adamretter

Updates ZStd and Snappy to the latest versions.

2021-12-16 22:50 UTC, mrambacher approved these changes
LGTM.

2021-12-17 03:34 UTC, jay-zhuang commented
Is the CI failure related to this change?

2021-12-17 08:17 UTC, adamretter commented
@jay-zhuang Ooof! Yes, it looks like a problem with compiling Snappy on that specific platform, I will have to investigate:

```
/Users/distiller/project/snappy-1.1.9/snappy.cc:1033:36: error: invalid output constraint '=@ccz' in asm
      : [tag_type] "+r"(tag_type), "=@ccz"(is_literal));
                                   ^
1 error generated.
make[4]: *** [CMakeFiles/snappy.dir/snappy.cc.o] Error 1
make[3]: *** [CMakeFiles/snappy.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [libsnappy.a] Error 2
```

2022-02-18 01:21 UTC, ajkr requested changes
The CI shows checksum mismatches. Do they need to be updated?

2022-02-21 10:37 UTC, adamretter commented
@ajkr It is failing because downloading the artifacts yields HTTP 404 Not Found.

It looks like @jay-zhuang updated the CircleCI config overrides the URLs for the download of the artifacts.
@jay-zhuang Would you be able to upload the latest libraries please?

2022-03-01 03:11 UTC, jay-zhuang commented
I think there's failure even build locally (without using binaries from s3), please take a look:
```
/home/zjay/ws/rocksdb/snappy-1.1.9/snappy.cc:1017:8: warning: always_inline function might not be inlinable [-Wattributes]
 1017 | size_t AdvanceToNextTag(const uint8_t** ip_p, size_t* tag) {
      |        ^~~~~~~~~~~~~~~~
/home/zjay/ws/rocksdb/snappy-1.1.9/snappy.cc: In function 'std::pair<const unsigned char*, long int> snappy::DecompressBranchless(const uint8_t*, const uint8_t*, ptrdiff_t, T, ptrdiff_t) [with T = char*]':
/home/zjay/ws/rocksdb/snappy-1.1.9/snappy.cc:1017:8: error: inlining failed in call to always_inline 'size_t snappy::AdvanceToNextTag(const uint8_t**, size_t*)': function body can be overwritten at link time
/home/zjay/ws/rocksdb/snappy-1.1.9/snappy.cc:1097:43: note: called from here
 1097 |         size_t tag_type = AdvanceToNextTag(&ip, &tag);
      |                           ~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

zstd and sanppy binaries are uploaded.

2023-10-02 21:31 UTC, jowlyzhang commented
I have uploaded the latest versions for these libraries. Can you rerun all the failing tests? Thanks!

2023-10-02 21:42 UTC, jowlyzhang commented on Makefile
> +ZSTD_SHA256 ?= 98e9c3d949d1b924e28e01eccb7deed865eefebf25c2f21c702e5cd5b63b85e1
This one seems to have been updated to 9c4396cc829cfae319a6e2615202e82aad41372073482fce286fac78646d3ee4

2023-10-02 21:44 UTC, jowlyzhang commented
Snappy still have some build errors.

2023-10-03 16:41 UTC, jowlyzhang commented
Looks like snappy 1.1.9 has some compilation errors too.

2023-10-20 17:42 UTC, closed without merging

2023-10-20 18:45 UTC, adamretter commented
@cbi42 I am not seeing it also in the 8.7.fb branch yet?

2023-10-20 20:19 UTC, cbi42 commented
> @cbi42 I am not seeing it also in the 8.7.fb branch yet?

Yeah sorry, I just pushed it to 8.7.fb.