Expose load options capi
facebook/rocksdb pull request #9511
Opened 2022-02-07 10:45 UTC by sg20180546

check my code please #9233 
@ajkr

2022-02-08 02:06 UTC, ajkr requested changes
Mostly looks fine with me.

2022-02-08 02:06 UTC, ajkr commented on db/c.cc
> +struct rocksdb_column_family_descriptor_t {std::vector<ColumnFamilyDescriptor> rep;};
s/descriptor/descriptors/

2022-02-08 02:06 UTC, ajkr commented on db/c.cc
> +};
We don't need this struct, do we? Can the new functions return void?

2022-02-08 04:46 UTC, sg20180546 commented
@ajkr I change code with your feedback. Thank you!

2022-02-08 05:51 UTC, ajkr commented
Thanks for the updates. Do you have a test or explanation how the user can open a DB using options loaded from a file? This is the relevant DB open function I found: https://github.com/facebook/rocksdb/blob/d7c868b0624518134147ee98877c0f41d531c56f/db/c.cc#L825-L829

2022-02-09 15:13 UTC, sg20180546 commented
@ajkr I write test code, run test, and passed in my computer.
but one thinng that on my mind is options_filename in the c_test (snprintf).
thank you!

2022-02-10 04:31 UTC, ajkr reviewed
Thanks for the tests. I do not understand how `rocksdb_dboptions_t` and `rocksdb_column_family_descriptors_t` can be used after `rocksdb_load_latest_options()` populates them. For example, I do not see how we can pass them to a function like `rocksdb_open()`.

2022-02-15 06:33 UTC, sg20180546 commented
`  // Load the options file.
  DBOptions loaded_db_opt;
  std::vector<ColumnFamilyDescriptor> loaded_cf_descs;
  ConfigOptions config_options;
  s = LoadLatestOptions(config_options, kDBPath, &loaded_db_opt,
                        &loaded_cf_descs);
  assert(s.ok());
  assert(loaded_db_opt.create_if_missing == db_opt.create_if_missing);

  // Initialize pointer options for each column family
  for (size_t i = 0; i < loaded_cf_descs.size(); ++i) {
    auto* loaded_bbt_opt =
        loaded_cf_descs[0]
            .options.table_factory->GetOptions<BlockBasedTableOptions>();
    // Expect the same as BlockBasedTableOptions will be loaded form file.
    assert(loaded_bbt_opt->block_size == bbt_opts.block_size);
    // However, block_cache needs to be manually initialized as documented
    // in rocksdb/utilities/options_util.h.
    loaded_bbt_opt->block_cache = cache;
  }
  // In addition, as pointer options are initialized with default value,
  // we need to properly initialized all the pointer options if non-defalut
  // values are used before calling DB::Open().
  assert(loaded_cf_descs[0].options.compaction_filter == nullptr);
  loaded_cf_descs[0].options.compaction_filter = compaction_filter.get();

  // reopen the db using the loaded options.
  std::vector<ColumnFamilyHandle*> handles;
  s = DB::Open(loaded_db_opt, kDBPath, loaded_cf_descs, &handles, &db);
  assert(s.ok());
`

2022-02-15 06:35 UTC, sg20180546 commented
`  // Load the options file.
  DBOptions loaded_db_opt;
  std::vector<ColumnFamilyDescriptor> loaded_cf_descs;
  ConfigOptions config_options;
  s = LoadLatestOptions(config_options, kDBPath, &loaded_db_opt,
                        &loaded_cf_descs);
  assert(s.ok());
  assert(loaded_db_opt.create_if_missing == db_opt.create_if_missing);

  // Initialize pointer options for each column family
  for (size_t i = 0; i < loaded_cf_descs.size(); ++i) {
    auto* loaded_bbt_opt =
        loaded_cf_descs[0]
            .options.table_factory->GetOptions<BlockBasedTableOptions>();
    // Expect the same as BlockBasedTableOptions will be loaded form file.
    assert(loaded_bbt_opt->block_size == bbt_opts.block_size);
    // However, block_cache needs to be manually initialized as documented
    // in rocksdb/utilities/options_util.h.
    loaded_bbt_opt->block_cache = cache;
  }
  // In addition, as pointer options are initialized with default value,
  // we need to properly initialized all the pointer options if non-defalut
  // values are used before calling DB::Open().
  assert(loaded_cf_descs[0].options.compaction_filter == nullptr);
  loaded_cf_descs[0].options.compaction_filter = compaction_filter.get();

  // reopen the db using the loaded options.
  std::vector<ColumnFamilyHandle*> handles;
  s = DB::Open(loaded_db_opt, kDBPath, loaded_cf_descs, &handles, &db);
  assert(s.ok());
`

2022-02-16 00:05 UTC, sg20180546 commented
@riversand963

2022-02-16 12:26 UTC, mrambacher requested changes
I think this is more complicated than it needs to be.  I suggest only adding three new APIs:

extern ROCKSDB_LIBRARY_API int rocksdb_load_options_from_file(const char* filename,
rocksdb_env_t* env, int ignore_unknown_optons,
rocksdb_cache_t* cache, 
rocksdb_options_t*** options,
char*** column_families,
char** errptr);

extern ROCKSDB_LIBRARY_API int rocksdb_load_latest_options(const char* dbpath,
rocksdb_env_t* env, int ignore_unknown_optons,
rocksdb_cache_t* cache, 
rocksdb_options_t*** options,
char*** column_families,
char** errptr);

extern ROCKSDB_LIBRARY_API void rocksdb_list_options_destroy(rocksdb_options_t** list, int sz);

The "load" methods will give you a list of options and column family names suitable for calling the DB create methods for column families.  The return code can be the size of the two lists (options_t, column_family_names).  

Note that there is already a method for deleting a list of column family names, so a new one is not needed.

2022-07-06 13:50 UTC, closed without merging

2022-07-06 13:50 UTC, sg20180546 commented
x